version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest  # PostgreSQL with pgvector preinstalled
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./pgdata:/var/lib/postgresql/data

